version: '3.3'

services:
  redis:
    container_name: "redis_dev"
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/db/redis/dev/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  mongo:
    container_name: "mongo_dev"
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db/mongo/dev/data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    container_name: "web_dev"
    image: dev
    env_file: .env.development
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./app:/usr/src/app
      - ./bin:/usr/src/bin
      - ./config:/usr/src/config
      - ./public:/usr/src/public