version: '3.3'

services:
  web_dev:
    container_name: "web_dev"
    image: dev
    env_file: .env.development
    restart: always
    links:
      - mongo_dev
      - redis_dev
    depends_on:
      - mongo_dev
      - redis_dev
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./src:/usr/app/src
      - ./bin:/usr/app/bin
