version: '3.3'

services:
  redis:
    container_name: "redis_prod"
    image: redis
    restart: always
    volumes:
      - ./data/db/redis/prod/data:/data
    entrypoint: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  mongo:
    container_name: "mongo_prod"
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db/mongo/prod/data:/data/db
    healthcheck:
      test: ["CMD", "mongo-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    container_name: "web_prod"
    image: prod
    restart: always
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"