version: '3.3'

services:
  redis:
    container_name: redis_dev
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
          - ./data/db/redis/devdata:/data
  mongo:
    container_name: mongo_dev
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db/mongo/devdata:/data/db
    ports:
      - "27017:27017"
  web:
    container_name: web_dev
    image: hollote/auth_app_dev
    restart: always
    environment:
      - MONGO_STORE_URI=mongodb://mongo:27017/baseNodeJs
      - REDIS_STORE_URI=//redis:6379
      - REDIS_STORE_SECRET=secret
      - NODE_ENV=development
      - PORT=3001
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./server/app:/usr/src/app
      - ./server/bin:/usr/src/bin
      - ./server/config:/usr/src/config
      - ./server/public:/usr/src/public