version: '3.3'

services:
  redis:
    container_name: "redis_prod"
    image: redis
    restart: always
    volumes:
      - ./data/db/redis/prod/data:/data
    entrypoint: redis-server --appendonly yes
  mongo:
    container_name: "mongo_prod"
    image: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db/mongo/prod/data:/data/db
  web:
    container_name: "web_prod"
    image: prod
    restart: always
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"